### ISSUE TITLE
Bullets pass through walls

### ISSUE THREAD

**Issue by TheGemDev** [Gdevelop-game/GDevelop-Open-Game#158]
bullets pass through walls during long fire at  a specific place
![Screenshot (51)](https://user-images.githubusercontent.com/53819287/97349395-b7ebb580-188f-11eb-883c-136ad8f0d72b.png)

**Comment by dark00shadow** [comment]
hmmm hopfully this is simple to fix :)

**Comment by dark00shadow** [comment]
got a couple of ideas on how to fix(ill try the idea from Leo Red first then mine i like the idea)

**Comment by dark00shadow** [comment]
i belive bug is now fixed
