### ISSUE TITLE
Bullets getting deleted after some distance

### ISSUE THREAD

**Issue by Midhil457** [Gdevelop-game/GDevelop-Open-Game#173]
. It not really a bug as it only happens when you are in godmode. The bullets gets deleted after a distance. Removing the existing code for that and adding delete when outside of screen should fix it.
![Screenshot from 2020-11-11 18-45-02](https://user-images.githubusercontent.com/73597906/98819758-485ef400-2453-11eb-952f-89677c5ac393.png)

**Comment by TheGemDev** [comment]
Yes but that is not a major issue as the godmod is just a test mainly for speed in transportation. it would be taken out before the release.

**Comment by Midhil457** [comment]
I am concerned if it will happen on big screens

**Comment by dark00shadow** [comment]
its okay if people see it its the range of the weapon

**Comment by Midhil457** [comment]
Then, it will need some kind of animation as currently it looks very artificial.

**Comment by dark00shadow** [comment]
> Then, it will need some kind of animation as currently it looks very artificial.

agreed wat will it be though

**Comment by Midhil457** [comment]
Maybe, like some tiny grey explosions. Showing that the bullet burst.
