### ISSUE TITLE
Cannot try the game

### ISSUE THREAD

**Issue by HiranChaudhuri** [Gdevelop-game/GDevelop-Open-Game#174]
https://gdevelop-game.github.io/GDevelop-Open-Game/
In my Ubuntu 18 Firefox browser I just see a gray canvas instead of any web page or game.

Then I tried to download the Linux version, but it seems the artifact is inaccessible. Clicking it does not trigger any download.

If the game still building successfully? Is it just me to experience this problem?

**Comment by Midhil457** [comment]
Can you share a screenshot. I think it is because the default scene is still empty. It also might be a build error.

**Comment by dark00shadow** [comment]
i belive the web exporter thingee is bugged and wont work for all of us you can correct me if wrong

**Comment by dark00shadow** [comment]
but if it dont run in gdev idk why

**Comment by HiranChaudhuri** [comment]
> I think it is because the default scene is still empty (The last time I checked) and it is being shown to you. It also might be a build error.

My gut feeling is there is no build error. The game takes some time to load to 100%, and during that time I can see the splash screen and the counter. Only after that the screen is gray (and after I take the screenshot it is black). So it seems more reasonable to saz the default scene is empty. I did not look at the source code though.

**Comment by Midhil457** [comment]
We talked about it in discord and found it the problem with the auto export and it will be fixed ASAP.

**Comment by dark00shadow** [comment]
what leo red said it will get fixed soon so from what ive seen on discord its auto export with bbtext i think it was so soon hopfully it will get fixed(i personally wont be able to do it rn or tmmr(aka today for me cuz its 6am almost 7am)
